# 01 - Descriptive Statistics

Sample characteristics, demographics, feedback, and conversation metrics.

In [1]:
source("00_setup.R")

Warning message:
“package ‘ggplot2’ was built under R version 4.3.3”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Warning message:
“package ‘jsonlite’ was built under R version 4.3.3”

Attaching package: ‘jsonlite’


The following object is masked from ‘package:purrr’:

    flatten


Loading pre-processed data...

Loaded: 24 participants, 192 observations, 96 chat observations


=== Data Loaded ===

Participants: 24

Total observations (data_long): 192

Chat observations (data_chat_analysis): 96

## Column Names

In [2]:
#names(data)

## Feedback Summary

In [3]:
# General feedback
data %>%
  filter(!is.na(debrief_general_feedback) & debrief_general_feedback != "" & debrief_general_feedback != "None" 
         & debrief_general_feedback != "No" & debrief_general_feedback != "NO" & debrief_general_feedback != "none" & debrief_general_feedback != "N/a" ) %>%
  dplyr::select(participant_id, condition, debrief_general_feedback)

# Persuasion descriptions (from those who noticed)
data %>%
  filter(!is.na(debrief_persuasion_description) & debrief_persuasion_description != "" & debrief_persuasion_description != "None" 
         & debrief_persuasion_description != "No" & debrief_persuasion_description != "NO" & debrief_persuasion_description != "none" & debrief_persuasion_description != "N/a") %>%
  dplyr::select(participant_id, condition, debrief_persuasion_description)

# Change descriptions (from those who changed mind)
data %>%
  filter(!is.na(debrief_change_description) & debrief_change_description != "" & debrief_change_description != "None" 
         & debrief_change_description != "No" & debrief_change_description != "NO" & debrief_change_description != "none" & debrief_change_description != "N/a") %>%
  dplyr::select(participant_id, condition, debrief_change_description)

   participant_id condition
1  25             neutral
2  24             persuade_info
3  22             neutral
4  45             persuade_demo
5  44             neutral
6  47             persuade
7  46             neutral
8  48             persuade_info
9  57             neutral
10 60             persuade_info
11 58             persuade_demo
12 62             persuade_demo
   debrief_general_feedback
1  The study broke after the time limit of 1 chat was up and did not let me continue until I closed the study, reopened it and wait another 5 minutes for the next button to become clickable again.
2  I didn't run into any issues!
3  very interesting study! The timer didn't work properly, though - it prevented me from submitting my points until after it ran out completely
4  This was a very interesting study and made me really think about how I view right and wrong.
5  The study was excellent and there were no technical issues.
6  good study
7  The study was clear and interesting.
8  GOOD STUDY
9  I enjoyed it If that is word, made me think and reminded me to have kindness
10 No, this was an interesting study and made me really think. Thank you for letting me take part.
11 This was extremely interesting.
12 good study

   participant_id condition
1  25             neutral
2  24             persuade_info
3  22             neutral
4  23             persuade_demo
5  26             persuade_demo
6  45             persuade_demo
7  44             neutral
8  47             persuade
9  49             persuade_info
10 48             persuade_info
11 52             neutral
12 51             persuade_info
13 57             neutral
14 60             persuade_info
15 54             persuade_info
16 55             persuade
17 58             persuade_demo
18 64             persuade_info
19 59             persuade_info
   debrief_persuasion_description
1  It might not have explicitly tried to persuade me but, it made arguments for its way of thinking which is trying to persuade me in a way.
2  When the AI stated a different opinion than me at the start of a conversation, it would not budge on its stance at all. Even if I brought up very good points, it just kept reinforcing the same thing over and over.
3  It kept saying that it understood my point of view, but disagreed with it and explained why.
4  The AI would argument my point
5  I could tell when it was opposed, and seemed unwilling to concede to me, rather trying to get me to concede towards its view.
6  The AI often reinforced my initial opinion and focused on arguments that supported my position. In some cases, it used emotional examples or personal perspectives, such as discussing families or responsibilities, to make its point more persuasive.
7  I feel like the AI was trying to change my opinion to value everyone's life the same, regardless of the situation. In some circumstance's I did not agree because there were many lives at stake compared to just one persons life.
8  I was disagreeing with the ai opinion and it tried to convince me
9  Reflected your previous views back at you in a slightly stronger, more unified direction, Framed each dilemma as a forced binary choice between “dignity rule” vs “outcome maximization
10 I disagreed with the AI And it persuaded me to on the decision
11 It seemed to be very staunch in it's argument and every time I offered my differing opinion, it would try to persuade me otherwise.
12 They used facts to inform me of how best to make a decision.
13 Only on one question, about the guerrilla group, but I assume that was because It was offering me a differing opinion
14 When we have different opinions on what was moral and what was not it wanted me to see it from a different point of view and would continue to persuade me that way.
15 When I raised a point, it always found a way to provide a counter argument, or it would ask me a question to counteract what I was saying/make me question my own point.
16 It kept asking me questions like: wouldn't you agree... and don't you think this is the right choice...
17 It was trying to push its side of the dilemmas, while accepting mine. It wasn't overly pushy, but kept reiterating its side.
18 IT'S TRYING TO PERSUADE ME
19 I noticed the AI wanting me to change my opinion, but it was done in a way which was considered and not pressurising.

   participant_id condition
1  25             neutral
2  24             persuade_info
3  22             neutral
4  45             persuade_demo
5  47             persuade
6  49             persuade_info
7  48             persuade_info
8  51             persuade_info
9  57             neutral
10 60             persuade_info
11 54             persuade_info
12 59             persuade_info
   debrief_change_description
1  It didn't make me switch from morally right to morally wrong but after having to defend my points it sometimes led me to the more extreme scale of morality instead of some middle ground.
2  None of the discussions changed my mind.
3  The AI shifted from saying one doesn't have a moral responsibility to kill someone to save others to saying one does (in the last dilemma case).
4  The discussions did not completely change my opinions, but they made me consider perspectives I had not thought of initially. In a few cases, such as the ransom and the submarine scenarios, I became more aware of the competing moral considerations and changed my rating slightly.
5  I saw them understandable and ethically fit
6  What changed was less about switching to a completely different moral view and more about how I prioritized the principles in the trade-offs.
7  It was ethically acceptable on what it we discussed on
8  The one regarding the tunnel - I failed to realize other lives would be lost.
9  again the guerrilla group was quite persuasive and caused me to re think my assumption
10 The conversation about the nurse was where my perspective was changed because of the AI. The AI made a good argument that if the nurse hit the switch, she would be directly involved in the death of someone versus letting it happen naturally.
11 Certain dilemmas e.g the submarine situation and shooting a crew member. The AI bot made me reevaluate my opinion and offered a different perspective/things I didn't thoroughly consider i.e. actually carrying out the shooting of my own crew member.
12 I changed my mind about paying the ransom for the journalist based on my back and forth with the AI about the different moral considerations of the situation as a whole.

## Persuasion Awareness & Self-Report

In [4]:
# Noticed persuasion - overall
data %>%
  count(debrief_noticed_persuasion) %>%
  mutate(pct = round(n / sum(n) * 100, 1))

# Noticed persuasion - by condition
data %>%
  count(condition, debrief_noticed_persuasion) %>%
  group_by(condition) %>%
  mutate(pct = round(n / sum(n) * 100, 1)) %>%
  filter(debrief_noticed_persuasion == TRUE) %>%
  dplyr::select(condition, n_noticed = n, pct_noticed = pct)

# Self-reported mind change - overall
data %>%
  count(debrief_changed_mind) %>%
  mutate(pct = round(n / sum(n) * 100, 1))

# Self-reported mind change - by condition
data %>%
  count(condition, debrief_changed_mind) %>%
  group_by(condition) %>%
  mutate(pct = round(n / sum(n) * 100, 1)) %>%
  filter(debrief_changed_mind == TRUE) %>%
  dplyr::select(condition, n_changed = n, pct_changed = pct)

  debrief_noticed_persuasion n  pct
1 FALSE                       5 20.8
2  TRUE                      19 79.2

  condition     n_noticed pct_noticed
1 neutral       5          83.3
2 persuade      2          50.0
3 persuade_demo 4          66.7
4 persuade_info 8         100.0

  debrief_changed_mind n  pct
1 FALSE                13 54.2
2  TRUE                11 45.8

  condition     n_changed pct_changed
1 neutral       3         50.0
2 persuade      1         25.0
3 persuade_demo 1         16.7
4 persuade_info 6         75.0

## Conversation Metrics

In [5]:
# Get all chat turn count columns
turn_cols <- names(data)[grepl("^chat_turn_count_", names(data))]

# Average turns per conversation (across all dilemmas)
data %>%
  dplyr::select(all_of(turn_cols)) %>%
  pivot_longer(everything(), names_to = "dilemma", values_to = "turns") %>%
  filter(!is.na(turns) & turns > 0) %>%
  summarise(
    n_conversations = n(),
    avg_turns_per_convo = mean(turns),
    min_turns = min(turns),
    max_turns = max(turns)
  )

  n_conversations avg_turns_per_convo min_turns max_turns
1 96              9.083333            3         19

## Time Spent on Experiment

In [6]:
# Calculate experiment duration (adjust column names if needed)
data %>%
  mutate(
    start_time = as.POSIXct(created_at),
    end_time = as.POSIXct(completed_at),
    duration_mins = as.numeric(difftime(end_time, start_time, units = "mins"))
  ) %>%
  summarise(
    avg_duration = mean(duration_mins, na.rm = TRUE),
    sd_duration = sd(duration_mins, na.rm = TRUE),
    min_duration = min(duration_mins, na.rm = TRUE),
    max_duration = max(duration_mins, na.rm = TRUE)
  )

  avg_duration sd_duration min_duration max_duration
1 45.32986     5.985486    36.7         57.08333

## AI Trust/Usage

In [7]:
# AI Trust (S-TIAS) summary
data %>%
  summarise(
    trust_mean = mean(debrief_stias_average, na.rm = TRUE),
    trust_sd = sd(debrief_stias_average, na.rm = TRUE),
    trust_min = min(debrief_stias_average, na.rm = TRUE),
    trust_max = max(debrief_stias_average, na.rm = TRUE)
  )

# AI usage frequency
data %>% count(debrief_ai_usage_frequency) %>% mutate(pct = round(n / sum(n) * 100, 1))

# AI tools used (split by comma, count each tool separately)
data %>%
  dplyr::select(participant_id, debrief_ai_tools_used) %>%
  filter(!is.na(debrief_ai_tools_used)) %>%
  separate_rows(debrief_ai_tools_used, sep = ",\\s*") %>%
  mutate(tool = str_trim(str_to_lower(debrief_ai_tools_used))) %>%
  count(tool, sort = TRUE) %>%
  mutate(pct = round(n / n_distinct(data$participant_id) * 100, 1))

# LLM provider distribution (which AI was used in experiment)
data %>% count(llm_provider) %>% mutate(pct = round(n / sum(n) * 100, 1))

  trust_mean trust_sd trust_min trust_max
1 5.138889   1.386326 1.333333  7

  debrief_ai_usage_frequency n  pct
1 often                      12 50.0
2 sometimes                   7 29.2
3 very_often                  5 20.8

  tool       n  pct
1 chatgpt    21 87.5
2 gemini     14 58.3
3 claude      7 29.2
4 copilot     7 29.2
5 perplexity  1  4.2

  llm_provider n  pct
1 anthropic    11 45.8
2 qwen         13 54.2

## Demographics

In [8]:
# Demographics summary
message("=== PARTICIPANT DEMOGRAPHICS ===\n")

# Age
message("Age:")
data %>%
summarise(
  n = sum(!is.na(demographics_age)),
  mean = round(mean(demographics_age, na.rm = TRUE), 1),
  sd = round(sd(demographics_age, na.rm = TRUE), 1),
  min = min(demographics_age, na.rm = TRUE),
  max = max(demographics_age, na.rm = TRUE)
) %>%
print()

# Gender
message("\nGender:")
data %>%
count(demographics_gender) %>%
mutate(pct = round(n / sum(n) * 100, 1)) %>%
print()

# Education
message("\nEducation:")
data %>%
count(demographics_education) %>%
mutate(pct = round(n / sum(n) * 100, 1)) %>%
arrange(desc(n)) %>%
print()

# Native English
message("\nNative English Speaker:")
data %>%
count(demographics_native_english) %>%
mutate(pct = round(n / sum(n) * 100, 1)) %>%
print()

# Condition distribution
message("\nCondition:")
data %>%
count(condition) %>%
mutate(pct = round(n / sum(n) * 100, 1)) %>%
print()

# LLM provider distribution
message("\nLLM Provider:")
data %>%
count(llm_provider) %>%
mutate(pct = round(n / sum(n) * 100, 1)) %>%
print()

# AI usage frequency (if available)
if ("ai_usage_frequency" %in% names(data)) {
message("\nAI Usage Frequency:")
data %>%
  count(ai_usage_frequency) %>%
  mutate(pct = round(n / sum(n) * 100, 1)) %>%
  print()
}

# Demographics visualization
demo_age <- ggplot(data, aes(x = demographics_age)) +
geom_histogram(binwidth = 5, fill = "#3498DB", color = "white") +
labs(title = "Age Distribution", x = "Age", y = "Count") +
theme_minimal()

demo_gender <- data %>%
count(demographics_gender) %>%
ggplot(aes(x = reorder(demographics_gender, -n), y = n, fill = demographics_gender)) +
geom_col() +
geom_text(aes(label = n), vjust = -0.3) +
labs(title = "Gender", x = "", y = "Count") +
theme_minimal() +
theme(legend.position = "none")

demo_education <- data %>%
count(demographics_education) %>%
ggplot(aes(x = reorder(demographics_education, n), y = n)) +
geom_col(fill = "#3498DB") +
geom_text(aes(label = n), hjust = -0.3) +
coord_flip() +
labs(title = "Education", x = "", y = "Count") +
theme_minimal()

=== PARTICIPANT DEMOGRAPHICS ===


Age:

# A tibble: 1 × 5
      n  mean    sd   min   max
  <int> <dbl> <dbl> <dbl> <dbl>
1    24  37.5  13.1    20    79

Gender:

# A tibble: 2 × 3
  demographics_gender     n   pct
  <chr>               <int> <dbl>
1 female                 14  58.3
2 male                   10  41.7

Education:

# A tibble: 5 × 3
  demographics_education     n   pct
  <chr>                  <int> <dbl>
1 bachelor                  10  41.7
2 master                     5  20.8
3 some_college               5  20.8
4 high_school                3  12.5
5 doctorate                  1   4.2

Native English Speaker:

# A tibble: 1 × 3
  demographics_native_english     n   pct
  <lgl>                       <int> <dbl>
1 TRUE                           24   100

Condition:

# A tibble: 4 × 3
  condition         n   pct
  <chr>         <int> <dbl>
1 neutral           6  25
2 persuade          4  16.7
3 persuade_demo     6  25
4 persuade_info     8  33.3

LLM Provider:

# A tibble: 2 × 3
  llm_provider     n   pct
  <chr>        <int> <dbl>
1 anthropic       11  45.8
2 qwen            13  54.2

In [9]:
# =============================================================================
# Descriptive Statistics - Summary Tables
# =============================================================================

message("=== CREATING DESCRIPTIVE SUMMARY TABLES ===\n")

library(gridExtra)
library(grid)

# Calculate all stats
n_total <- nrow(data)
age_mean <- round(mean(data$demographics_age, na.rm = TRUE), 1)
age_sd <- round(sd(data$demographics_age, na.rm = TRUE), 1)
age_range <- sprintf("%d-%d", min(data$demographics_age, na.rm = TRUE), max(data$demographics_age, na.rm = TRUE))

# Gender
gender_counts <- table(data$demographics_gender)
n_female <- ifelse("female" %in% names(gender_counts), as.numeric(gender_counts["female"]), 0)
n_male <- ifelse("male" %in% names(gender_counts), as.numeric(gender_counts["male"]), 0)

# Education (using actual values from data)
edu_counts <- table(data$demographics_education)
n_hs <- ifelse("high_school" %in% names(edu_counts), as.numeric(edu_counts["high_school"]), 0)
n_some_college <- ifelse("some_college" %in% names(edu_counts), as.numeric(edu_counts["some_college"]), 0)
n_bach <- ifelse("bachelor" %in% names(edu_counts), as.numeric(edu_counts["bachelor"]), 0)
n_mast <- ifelse("master" %in% names(edu_counts), as.numeric(edu_counts["master"]), 0)
n_doc <- ifelse("doctorate" %in% names(edu_counts), as.numeric(edu_counts["doctorate"]), 0)

trust_mean <- round(mean(data$debrief_stias_average, na.rm = TRUE), 2)
trust_sd <- round(sd(data$debrief_stias_average, na.rm = TRUE), 2)

condition_counts <- table(data$condition)
llm_counts <- table(data$llm_provider)

# -----------------------------------------------------------------------------
# TABLE 1: Sample Demographics
# -----------------------------------------------------------------------------

demo_table <- data.frame(
  Variable = c("Total N", 
               "Age, M (SD)", 
               "Age range",
               "Gender: Female",
               "Gender: Male",
               "Education: High School",
               "Education: Some College",
               "Education: Bachelor's",
               "Education: Master's",
               "Education: Doctorate",
               "AI Trust (S-TIAS), M (SD)"),
  Value = c(
    as.character(n_total),
    sprintf("%.1f (%.1f)", age_mean, age_sd),
    age_range,
    sprintf("%d (%.0f%%)", n_female, n_female/n_total*100),
    sprintf("%d (%.0f%%)", n_male, n_male/n_total*100),
    sprintf("%d (%.0f%%)", n_hs, n_hs/n_total*100),
    sprintf("%d (%.0f%%)", n_some_college, n_some_college/n_total*100),
    sprintf("%d (%.0f%%)", n_bach, n_bach/n_total*100),
    sprintf("%d (%.0f%%)", n_mast, n_mast/n_total*100),
    sprintf("%d (%.0f%%)", n_doc, n_doc/n_total*100),
    sprintf("%.2f (%.2f)", trust_mean, trust_sd)
  )
)

# Create table with styling
table_theme <- ttheme_default(
  core = list(
    fg_params = list(fontsize = 14, hjust = 0, x = 0.05),
    bg_params = list(fill = c("grey95", "white"))
  ),
  colhead = list(
    fg_params = list(fontface = "bold", fontsize = 16),
    bg_params = list(fill = "grey75")
  )
)

t1 <- tableGrob(demo_table, rows = NULL, theme = table_theme)
title1 <- textGrob("Sample Demographics", gp = gpar(fontsize = 18, fontface = "bold"))

png("figures/desc_table_demographics.png", width = 1200, height = 900, res = 150)
grid.newpage()
grid.arrange(title1, t1, nrow = 2, heights = c(0.1, 0.9))
dev.off()

message("Saved: figures/desc_table_demographics.png")

# -----------------------------------------------------------------------------
# TABLE 2: Study Design / Conditions
# -----------------------------------------------------------------------------

design_table <- data.frame(
  Variable = c("Condition: Neutral",
               "Condition: Persuade",
               "Condition: Persuade (Demo)",
               "Condition: Persuade (Info)",
               "LLM: Claude (Anthropic)",
               "LLM: Qwen"),
  Value = c(
    sprintf("%d (%.0f%%)", condition_counts["neutral"], condition_counts["neutral"]/n_total*100),
    sprintf("%d (%.0f%%)", condition_counts["persuade"], condition_counts["persuade"]/n_total*100),
    sprintf("%d (%.0f%%)", condition_counts["persuade_demo"], condition_counts["persuade_demo"]/n_total*100),
    sprintf("%d (%.0f%%)", condition_counts["persuade_info"], condition_counts["persuade_info"]/n_total*100),
    sprintf("%d (%.0f%%)", llm_counts["anthropic"], llm_counts["anthropic"]/n_total*100),
    sprintf("%d (%.0f%%)", llm_counts["qwen"], llm_counts["qwen"]/n_total*100)
  )
)

t2 <- tableGrob(design_table, rows = NULL, theme = table_theme)
title2 <- textGrob("Study Design", gp = gpar(fontsize = 18, fontface = "bold"))

png("figures/desc_table_design.png", width = 1200, height = 500, res = 150)
grid.newpage()
grid.arrange(title2, t2, nrow = 2, heights = c(0.15, 0.85))
dev.off()

message("Saved: figures/desc_table_design.png")

# Print tables
message("\n=== DEMOGRAPHICS ===")
print(demo_table)
message("\n=== STUDY DESIGN ===")
print(design_table)

=== CREATING DESCRIPTIVE SUMMARY TABLES ===


Warning message:
“package ‘gridExtra’ was built under R version 4.3.3”

Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine

pdf
  2

Saved: figures/desc_table_demographics.png

pdf
  2

Saved: figures/desc_table_design.png


=== DEMOGRAPHICS ===

                    Variable       Value
1                    Total N          24
2                Age, M (SD) 37.5 (13.1)
3                  Age range       20-79
4             Gender: Female    14 (58%)
5               Gender: Male    10 (42%)
6     Education: High School     3 (12%)
7    Education: Some College     5 (21%)
8      Education: Bachelor's    10 (42%)
9        Education: Master's     5 (21%)
10      Education: Doctorate      1 (4%)
11 AI Trust (S-TIAS), M (SD) 5.14 (1.39)

=== STUDY DESIGN ===

                    Variable    Value
1         Condition: Neutral  6 (25%)
2        Condition: Persuade  4 (17%)
3 Condition: Persuade (Demo)  6 (25%)
4 Condition: Persuade (Info)  8 (33%)
5    LLM: Claude (Anthropic) 11 (46%)
6                  LLM: Qwen 13 (54%)